name: BDD Test Generation
run-name: Running - Workflow BDD Test Generation

on:
  push:
  workflow_dispatch:
  
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          pip install groq pytest pytest-bdd
 
      - name: Generate BDD from criterios.md
        run: python ai/generate_bdd.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
 
      - name: Generate Tests from BDD
        run: python ai/generate_tests_from_bdd.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
 
      - name: Run Tests
        run: pytest ai/tests --maxfail=1 --disable-warnings -q
        continue-on-error: true

      - name: Commit BDD and tests
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ai/bdd/*.feature ai/tests/*.py
          git commit -m "🤖 Gerando BDDs e testes automáticos [skip ci]" || echo "Nada para commitar"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
