name: Execução de testes
run-name: Running - Execução de testes

on:
  push:
    branches-ignore: 
      - main
  workflow_dispatch:
 
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Execução testes
        run: |
            npm init -y
            npm i -D @playwright/test typescript ts-node
            npx playwright install --with-deps
            npx playwright test

