name: Execução de testes
run-name: Running - Execução de testes

on:
  push:
    branches-ignore: 
      - main
  workflow_dispatch:
 
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: npm init
        run: |
          npm init -y
 
      - name: npm i 
        run: |
          npm i -D @playwright/test typescript ts-node
      - name: npm x 
        run: |
          npx playwright install --with-deps
      - name: Rodando os testes 
        run: |
          npx playwright test

