name: Execucao de testes
run-name: Running - Execução de testes

on:
  push:
    branches: 
      - feat-pipeline-conexao
  workflow_dispatch:
 
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Clone do repositório
        run: |
          git clone https://github.com/Felipe-Janazi/integration-agent.git

      - name: Entrando no repositório
        run: |
          cd integration-agent
          git checkout feat-pipeline-conexao

          
      - name: Instalação de dependências
        run: |
          npm init -y
          npm i -D @playwright/test typescript ts-node

      - name: Execução de testes
        run: |
            npx playwright install
            npx playwright test > test-results/terminal.log 2>&1
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-results
          path: test-results

      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          pip install groq pytest pytest-bdd
 
      - name: Generate analises
        run: python ai/generate_analise.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Commit analises
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ai/analysis/*
          git commit -m "🤖 Gerando analises e conselhos automáticos [skip ci]" || echo "Nada para commitar"
          git push
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
