name: Execução de testes
run-name: Running - Execução de testes

on:
  push:
    branches-ignore: 
      - main
  workflow_dispatch:
 
jobs:
  generate-and-test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Clone do repositório
        run: |
          git clone https://github.com/Felipe-Janazi/integration-agent.git

      - name: Entrando no repositório
        run: |
          cd integration-agent
          git checkout feat-pipeline-conexao

          
      - name: Instalação de dependências
        run: |
          npm init -y
          npm i -D @playwright/test typescript ts-node
          sudo npx playwright install --with-deps
          
      - name: Debug Playwright deps
        run: |
            node -v
            npm -v
            npm ls @playwright/test || true
            node -e "console.log('resolved:', require.resolve('@playwright/test'))"

      - name: Execução de testes
        run: |
            npx playwright test

